const lambdaNamespace = 'AWS/Lambda';
const apiGatewayNamespace = 'AWS/ApiGateway';

module.exports = {
  functionInvocations: {
    namespace: lambdaNamespace,
    enabled: true,
    actionsEnabled: true,
    type: 'static',
    metric: 'Invocations',
    threshold: 100,
    statistic: 'Sum',
    period: 60,
    evaluationPeriods: 1,
    datapointsToAlarm: 1,
    comparisonOperator: 'GreaterThanOrEqualToThreshold',
  },
  functionErrors: {
    namespace: lambdaNamespace,
    enabled: true,
    actionsEnabled: true,
    type: 'static',
    metric: 'Errors',
    threshold: 1,
    statistic: 'Sum',
    period: 60,
    evaluationPeriods: 1,
    datapointsToAlarm: 1,
    comparisonOperator: 'GreaterThanOrEqualToThreshold',
  },
  functionDuration: {
    namespace: lambdaNamespace,
    enabled: true,
    actionsEnabled: true,
    type: 'static',
    metric: 'Duration',
    threshold: 500,
    statistic: 'Average',
    period: 60,
    evaluationPeriods: 1,
    datapointsToAlarm: 1,
    comparisonOperator: 'GreaterThanOrEqualToThreshold',
  },
  functionThrottles: {
    namespace: lambdaNamespace,
    enabled: true,
    actionsEnabled: true,
    type: 'static',
    metric: 'Throttles',
    threshold: 1,
    statistic: 'Sum',
    period: 60,
    evaluationPeriods: 1,
    datapointsToAlarm: 1,
    comparisonOperator: 'GreaterThanOrEqualToThreshold',
  },
  functionErrorRate: {
    namespace: lambdaNamespace,
    enabled: true,
    actionsEnabled: true,
    type: 'errorRate',
    metric: 'CustomErrorRate',
    threshold: 5.0,
    statistic: 'Sum',
    period: 60,
    requestPeriod: 60,
    errorPeriod: 60,
    evaluationPeriods: 1,
    datapointsToAlarm: 1,
    comparisonOperator: 'GreaterThanOrEqualToThreshold',
    formula: 'error/request*100'
  },
  apiGateway5xxError: {
    namespace: apiGatewayNamespace,
    enabled: true,
    actionsEnabled: true,
    type: 'apiGateway5xxError',
    metric: '5XXError',
    threshold: 0,
    statistic: 'Sum',
    period: 60,
    evaluationPeriods: 1,
    comparisonOperator: 'GreaterThanThreshold',
    description: '5xx errors at API Gateway',
    isApiGatewayAlarm: true,
    resourcePrefix: '',
  },
  apiGateway4xxError: {
    namespace: apiGatewayNamespace,
    enabled: true,
    actionsEnabled: true,
    type: 'apiGateway4xxError',
    metric: '4XXError',
    threshold: 0,
    statistic: 'Sum',
    period: 60,
    evaluationPeriods: 1,
    comparisonOperator: 'GreaterThanThreshold',
    descrription: '4xx errors at API Gateway',
    isApiGatewayAlarm: true,
    resourcePrefix: '',
  },
};
